print (f"calculo de tiempo de viajes")
duracion_tramo1 = float(input("Dime la duracion del tramo 1: "))
duracion_tramo2 = float(input("Dime la duracion del tramo 2: "))
duracion_tramo3 = float(input("Dime la duracion del tramo 3: "))
duracion_tramo4 = float(input("Dime la duracion del tramo 4: "))
duracion_escala1 = float(input("dime la duracionde la escala 1: "))
duracion_escala2 = float(input("dime la duracion de la segunda escala 2: "))
tiempo_total = (duracion_tramo1 + duracion_tramo2 + duracion_tramo3 + duracion_tramo4 + duracion_escala1 + duracion_escala2)
print (f"El tiempo total de todos sus viajes es: {tiempo_total}")
