sistematico1 = int(input("Ingrese primer sistematico (max: 30): "))
sistematico2 = int(input("Ingresar segundo sistematico (max: 30): "))
sistematico3 = int(input("Ingrese tercer sistematico (max: 40): "))
nota = (sistematico1 + sistematico2 + sistematico3)
print("La nota del estudiantes es de: ", nota) 